
- name: Docker installation (App)
  hosts: app
  become: yes
  roles:
    - docker
  tags:
    - dockerinstall

- name: Wiki.js install and deploy
  hosts: app
  become: yes
  roles:
    - app
  tags:
    - appinstall

- name: Reverse proxy setup
  hosts: proxy
  become: yes
  roles:
    - proxy
  tags:
    - proxyinstall

- name: Install agent
  hosts: app
  become: yes
  roles:
    - agente
  tags:
    - agenteinstall